### ISSUE TITLE
Add support for hostkey when connecting via ssh

### ISSUE THREAD

**Issue by GeoffAliro** [ADTRAN/netconf_client#23]
connect_ssh currently doesn't allow for a ssh connection to pass in a hostkey to verify. netconf_client can pass this directly to paramiko when calling connect.

**Comment by APCBoston** [comment]
Pssst @GeoffAliro you should close your issue since your PR was merged :-)

(Also GH will do this for you if you preface the issue reference with one of the recognized closing keywords listed at https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

**Comment by JennToo** [comment]
Ah I can close it too, I haven't been keeping up with the issues
