### ISSUE TITLE
Connect.py should not set socket timeout to None

### ISSUE THREAD

**Issue by APCBoston** [ADTRAN/netconf_client#25]
Referencing this code in `connect.py`:  by setting `sock.settimeout(None)`, it becomes possible that a `send_rpc` call to a device hangs indefinitely if the device has gone into an unresponsive state without closing the connection.  It also violates the expectation of the calling code that the `timeout` parameter on `connect_ssh` will put the socket in timeout mode.  (I note as I am writing this that the docstring does say it's a timeout 'when connecting the socket`, but it's non-obvious until entering this failure mode that this timeout is changed to `None` after the connection is first established.  

https://github.com/ADTRAN/netconf_client/blob/645f29936a526255a5d428d18907007827c4fecd/netconf_client/connect.py#L48-L52

I'm not submitting a PR to fix only because it's not entirely clear to me what the intention was in setting this to `None` in the first place.

**Comment by JennToo** [comment]
TBH I have no idea why that's there either. We might have been using it internally during some weird testing (this library was originally designed to test edge case bugs we were seeing in our NETCONF servers that `ncclient` wouldn't enable us to do).

Because `timeout` currently only affects the initial TCP connection, I'm hesitant to re-use it for post-connect timeout. But I'd support a new argument for allowing a timeout to be set for general operation post-connection.

How does this sound?

 - A new parameter, `general_timeout` (I'm open to name suggestions, not really sure what to call this) replaces that `None` after the connection is made. It defaults to `None` to preserve existing behavior
 - A new parameter, `connection_timeout`, is added and is used as a replacement for `timeout`. It defaults to `None`, and if it's  `None` then the existing `timeout` parameter is used. If it's not `None`, it's used as the timeout for the initial connection
 - The `timeout` parameter is marked in the docs as deprecated in favor of the two new args.

I think that will enable backwards compatibility, preserving existing behavior while also enabling the socket timeout post-connection to be set. And it will also give the new parameters sane names (instead of having `timeout` + `general_timeout` in calling code, which I think would be very confusing)

**Comment by APCBoston** [comment]
That bifurcation works for me!  I might call the second new parameter `initial_timeout` because I think it's unclear whether "connection" in a name refers to the initial connection _event_ or the indefinitely-persistent connection that this code models as the `session` object.

**Comment by JennToo** [comment]
Released in 2.3.0!
